version: '1.0'
name: pipeline-20230619
displayName: build
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-1c682f38
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run docs:build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./docs/.vuepress/dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
